---
driver:
  name: docker
  provision_command: curl -L https://www.chef.io/chef/install.sh | bash

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[es-stack::default]
    attributes:
